version: '3.8'

services:
  expense_tracker_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense_tracker_app
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PORT=8080
